### ISSUE TITLE
[Feature] Disallow File Extension

### ISSUE THREAD

**Issue by its-miroma** [theoludwig/markdownlint-rule-relative-links#11]
## Description

[VitePress recommends](<https://vitepress.dev/guide/routing#linking-between-pages>) using relative links without file extensions. For example:

```md
[Correct](./file)
[Wrong](./file.md)
```

## Describe the solution you'd like

Please add an option (off by default) so that the linter warns of links with extensions.

## Describe alternatives you've considered

[`markdownlint-rule-search-replace`](<https://www.npmjs.com/package/markdownlint-rule-search-replace>) with this configuration:

```yaml
config:
  search-replace:
    - name: no-file-extension-in-links
    message: "Don't add the file extension to links"
    searchPattern: "/\\[(.*?)\\]\\((.*?)\\.md((?:#[a-z0-9-]+)?)\\)/g"
    replace: "[$1]($2$3)"
    searchScope: text
customRules:
  - ./node_modules/markdownlint-rule-search-replace/rule.js
```
